### ISSUE TITLE
Hide icon text for all window header icons

### ISSUE THREAD

**Issue by kristianserrano** [zeel01/monarch#50]
While trying to find a way to remove the text from the PopOut window header icon, I came up with the following CSS changes.

```css
.window-app.monarch-hand:not(.minimized) .window-header a {
    font-size: 0px;
    margin: 0;
}

.window-app.monarch-hand:not(.minimized) .window-header a i {
    font-size: var(--font-size-14);
}
```
This approach would remove the dependency on the `.header-button` class being added to every header button.
