### ISSUE TITLE
Override rotate on window resize icon

### ISSUE THREAD

**Issue by kristianserrano** [zeel01/monarch#54]
The current resize icon is diagonal and gives the impression that you can make the window bigger vertically as well as horizontally. When one attempts to resize, it feels strangely restricted. If the icon were a horizontal instead, the horizontal resize would feel more natural.

I think it would be pretty easy to override the current CSS:
```css
.window-app .window-resizable-handle i.fas {
    transform: rotate(45deg);
}
```
with
```css
.window-app.monarch .window-resizable-handle i.fas {
    transform: rotate(0deg);
}
```
